### ISSUE TITLE
After v0.3.0, smart-plug no longer outputs deviceInstance.getSysInfo when changing power state, brightness, or LED status

### ISSUE THREAD

**Issue by caseyjhol** [caseyjhol/node-red-contrib-tplink#10]
This previously output system info:
![image](https://user-images.githubusercontent.com/2874325/83800305-79492a80-a664-11ea-8d81-6ef113aef8ae.png)

**Comment by MaddyTP** [comment]
What is the benefit of emitting 'sysInfo' on state change when 'getPowerEvents' emits on state change?

**Comment by MaddyTP** [comment]
Since 'getInfo' isn't a supported emit event in TPLink-Smarthome-API it was not adapted for this release.  However, polling 'getInfo' can be accomplished with inject:

![image](https://user-images.githubusercontent.com/45469378/83803114-d93dd200-a660-11ea-8377-3bda3a9f22ac.png)

**Comment by caseyjhol** [comment]
What's the disadvantage? I have a flow that ends in setting the brightness of the light, which then passes sysInfo to a debug node and another node that stores sysInfo in a log. That no longer works after the update. Sure, I could call `'getInfo'` after, but now that's another node I need to add for no reason.

**Comment by MaddyTP** [comment]
> What's the disadvantage? I have a flow that ends in setting the brightness of the light, which then passes sysInfo to a debug node and another node that stores sysInfo in a log. That no longer works after the update. Sure, I could call `'getInfo'` after, but now that's another node I need to add for no reason.

Disadvantage could be undesired clutter of msg.payload.  Maybe a compromise is to create a optional polling event to emit 'sysInfo'?

**Comment by MaddyTP** [comment]
Alternatively, implementing the following supported events with bulb values for debug:

lightstate-off
lightstate-on
lightstate-update
lightstate-change

**Comment by MaddyTP** [comment]
I guess this would entirely depend whether the user is relying on emit events past the smart-plug node, as I am.  If so, then the user is likely doing something with the emitted events and would have to filter out the sysInfo to utilize any of the emitted events.  

![image](https://user-images.githubusercontent.com/45469378/83805174-3be49d00-a664-11ea-90ef-f111667eb275.png)

**Comment by caseyjhol** [comment]
Fixed in d8192aa.
