### ISSUE TITLE
Passing brightness as a string doesn't work

### ISSUE THREAD

**Issue by caseyjhol** [caseyjhol/node-red-contrib-tplink#11]

**Comment by MaddyTP** [comment]
Identified a fix for this issue...will have a new PR today.

**Comment by caseyjhol** [comment]
After testing v0.2.1, it looks like setting brightness as a string didn't work then either. Apparently I never implemented it. Could've sworn I did (especially since I put it in the docs).

**Comment by MaddyTP** [comment]
It wouldn't be difficult to implement, but it would be more reliable to set int values through properties since there are many.

Hue/Temperature/Brightness...

**Comment by caseyjhol** [comment]
Yea, might be more work than it's worth. I'm thinking we just remove the mention from the docs.

**Comment by MaddyTP** [comment]
Completely agree...it would be difficult to determine which property was being changed without the property.
