### ISSUE TITLE
getMeterInfo causes Error

### ISSUE THREAD

**Issue by Makrador** [caseyjhol/node-red-contrib-tplink#19]
Error:

msg : error
"ReferenceError: numeral is not defined"

easy to reproduce... inject getMeterInfo to smart Plug.---> Error
                                   inject getInfo to smart Plug.---> correct output
                                  inject getMeterEvents to smart Plug.---> no output

[{"id":"a889f81c.d693c8","type":"inject","z":"fe74e40c.2a26b8","name":"","topic":"","payload":"getMeterInfo","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":530,"wires":[["7e7c3292.4a421c","6fbbed1f.767a64","29dec093.afa3","aac0da4d.9ef5b8"]]},{"id":"6fbbed1f.767a64","type":"smart-plug","z":"fe74e40c.2a26b8","name":"steckdose-bierkühlschrank","device":"10.181.11.151","interval":10000,"eventInterval":1000,"payload":"getMeterInfo","payloadType":"info","x":350,"y":580,"wires":[["d15072ed.2b0d5","5708d747.945ca8"]],"info":"Commands\ngetInfo - Fetch the device information.\n\ngetCloudInfo - Fetch the device information from the cloud.\n\ngetQuickInfo - Fetch most popular proprieties, such as username, device consumption, mode, lighting state, and many more.\n\ngetMeterInfo - Fetch the current device consumption.\n\nclearEvents - Unsubscribe events.\n\neraseStats - Clear all the meter statistics."},{"id":"5708d747.945ca8","type":"debug","z":"fe74e40c.2a26b8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":540,"y":750,"wires":[]}]

getInfo works with output, all other command have no effect...

Node-Red running on Raspberry (v0.20.7)
Browser is Crome
everything worked (0.41) until yesterday upgrade to 0.42

**Comment by caseyjhol** [comment]
Fixed in v0.4.3.
