### ISSUE TITLE
Implement Per-device set state for KP400

### ISSUE THREAD

**Issue by uncled1023** [caseyjhol/node-red-contrib-tplink#20]
I currently have a couple Outdoor Plugs that I want to be able to set each plug separately.  This doesn't seem to work using the 'plug' parameter.  0 sets it for all, and 1/2 don't do anything.

**Comment by caseyjhol** [comment]
I just added a "debug" property to the smart-plug node. Please enable debug, and let me know what the output is.

**Comment by uncled1023** [comment]
Alright, here is the output from it: https://p.teknik.io/jFrwr

**Comment by caseyjhol** [comment]
Thanks - checking into this.

**Comment by caseyjhol** [comment]
@MaddyTP You have any thoughts on this?

**Comment by MaddyTP** [comment]
When was the last time firmware was updated? Internals should be the same as the HS107 which works fine...

**Comment by uncled1023** [comment]
It's currently on firmware 1.0.10

**Comment by MaddyTP** [comment]
It seems some people are having issues with firmware 1.0.10 in other environments, could be a firmware issue.  Can you try a hard reset (hold button for 15 seconds) and run through the setup/firmware update?

**Comment by uncled1023** [comment]
Interesting, so after a hard reset and setting it back up, it's now working correctly.  Seems like that firmware upgrade did something to the devices.

**Comment by MaddyTP** [comment]
Excellent!

**Comment by caseyjhol** [comment]
Glad to hear it's working!
