### ISSUE TITLE
"TypeError: Cannot read property 'getInfo' of undefined"

### ISSUE THREAD

**Issue by Stulander** [caseyjhol/node-red-contrib-tplink#34]
Node appears to be broken with HS110 firmware version 1.5.10 hardware version 2.1. Nodered version 1.0.6.

Also getting "Sorry. Your selected device is invalid!" when trying to edit node.

**Comment by caseyjhol** [comment]
What version of node-red-contrib-tplink are you using?

**Comment by Stulander** [comment]
0.4.3, latest version

**Comment by caseyjhol** [comment]
Please try v1.0.0-alpha.

**Comment by Stulander** [comment]
Will do, and assuming this fixes it I apologise in advance for not checking that before.

**Comment by caseyjhol** [comment]
No worries. It's an alpha release so I understand not noticing/trying it. I'm waiting for someone who has bulbs to test it before releasing a final version.

**Comment by Stulander** [comment]
Now I'm unable to connect to the plug at all, with error

`"Error connecting to device 192.168.1.59: Error: connect EHOSTUNREACH 192.168.1.59:9999"`

The Kasa app works - I'm able to switch the plug on and off. I looked up the MAC address on the DHCP server so I'm definitely connecting to the right IP address.

**Comment by caseyjhol** [comment]
I just released v1.0.0-alpha.1. It's a pretty small update, but it does address some memory leak issues. Please try upgrading to that and let me know if the issue persists.

**Comment by Stulander** [comment]
Same issue it seems. I think the TP-Link smart home API must be broken, the auto discover function can't find my HS110. I just tried the code found here: https://github.com/plasticrake/tplink-smarthome-api/issues/54 which also didn't work.

I tried changing the broadcast address to 192.168.1.255 as suggested which also didn't seem to fix it.

**Comment by Head** [comment]
Just want to leave here, sounds like a similar API change:
In v0.4.3 I get `"TypeError: Cannot read property 'emeter' of undefined"`.

tbh I don't know how to install the alpha version...

**Comment by Stulander** [comment]
It's just a case of copying the files in the archive to the correct directory. On my install it was something like /home/<username>/.node-red/nodes

Find the node-red-contrib-tplink folder and overwrite the files in there with the new ones, restart node-red and you should see that the node has been updated.

**Comment by caseyjhol** [comment]
@Head 

`npm i node-red-contrib-tplink@1.0.0-alpha.1`
