### ISSUE TITLE
Cannot set connection and event poll interval to 0

### ISSUE THREAD

**Issue by kozmoz** [caseyjhol/node-red-contrib-tplink#36]
**Describe the bug**
Cannot set both the connection poll interval and the event poll interval to 0 to disable it. When saved, it says those fields are required. It's mentioned in the README.md that 0 disables polling.

**To Reproduce**
1. Create new tplink node
2. Select just a random device
3. Set connection poll interval to 0
4. Set event poll interval to 0 
4. Click save and see the error

**Expected behavior**
Should save the 0 values without showing an error

**Desktop:**
 - OS: Raspberry Pi Debian: 8.0
 - Browser Safari: 13.1.2
 - node-red: 1.0.3
 - node-red-contrib-tplink: ^0.4.3
 - NodeJS: v10.22.0

**Additional context**
There's no way to disable polling

**Comment by kozmoz** [comment]
Yes now it works. I wasn’t aware the Readme is for the development version. 

Only minor issue is that the existing nodes didn’t exist anymore. Isn’t there a way to convert those nodes automatically. But everything is working fine now! 👍🏻

**Comment by hufftheweevil** [comment]
Unfortunately not. The node types are different.

**Comment by caseyjhol** [comment]
@hufftheweevil We probably should. I was just worried about breaking anybody's config.
