### ISSUE TITLE
Offline Event/Payload

### ISSUE THREAD

**Issue by GeerGuy** [caseyjhol/node-red-contrib-tplink#40]
It would be nice if when a device goes offline there was an event or payload to indicate it.

**Comment by hufftheweevil** [comment]
Just subscribe to `OnlineEvents` using the `startOnlineEvents` payload. That will emit for both online (in which case the output payload will be `true`) and offline (where the output payload will be `false`).

**Comment by GeerGuy** [comment]
Can't believe I missed that one.  Thanks

**Comment by hufftheweevil** [comment]
No worries!
