### ISSUE TITLE
Events names are wrongly documented

### ISSUE THREAD

**Issue by pagaille** [caseyjhol/node-red-contrib-tplink#44]
Hi,

Looking at the inline doc, there is a reference to the `startMeterUpdateEvents` event, that isn't recognised by the node. One has to use `startMeterEvents` as correctly explained in the README.md file.

I guess other events should be corrected as well.

Thanks

**Comment by caseyjhol** [comment]
Fixed - will be available in the next release (let me know if you see more incorrect event names).
