### ISSUE TITLE
Unexpected Node Error in node-red

### ISSUE THREAD

**Issue by Steve-Mcl** [caseyjhol/node-red-contrib-tplink#58]
**Describe the bug**
Your code uses `node.error` in the promise `.catch`  ([see here](https://github.dev/caseyjhol/node-red-contrib-tplink/blob/15aae36380263a40977a2634e8d340af49310610/nodes/kasa.js#L335)) which is causing `Node` instance to be `globalThis` and therefore the prototype doesnt contain expected objects and logging capabilities etc.

See issue thread for full details https://github.com/node-red/node-red/issues/3389

**To Reproduce**
See issue thread for full details https://github.com/node-red/node-red/issues/3389#issuecomment-1040139419 (**this comment includes a potential fix**)

**Expected behavior**
`Node` instance to be a node-red node instance (not `globalThis`)

**Screenshots**
See issue thread for full details https://github.com/node-red/node-red/issues/3389

**Desktop (please complete the following information):**
 - OS: All
 - Browser: N/A (server side issue)
 - Version: 1.0.0

**Comment by caseyjhol** [comment]
Resolved in v1.0.1
