### ISSUE TITLE
Unexpected Node Error

### ISSUE THREAD

**Issue by SDupuie** [caseyjhol/node-red-contrib-tplink#62]
Happens a few times per day on average.

I was told by the Node-RED Github to report it here. They also said to inform the author that calling node.error in a catch call back causes this error e.g. https://github.com/caseyjhol/node-red-contrib-tplink/blob/15aae36380263a40977a2634e8d340af49310610/nodes/kasa.js#L335

My Node-RED installation is being hosted on Mac OS X Monterey 12.5.1.

2 Sep 13:29:48 - [error] 
********************************************************************
Unexpected Node Error
********************************************************************
Info:
 Node object is not a node-red Node
Stack:
 Error: TCP Socket Closed. segment:0 hadError:false
    at Socket.<anonymous> (/Users/Scott/.node-red/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:104:31)
    at Object.onceWrapper (node:events:642:26)
    at Socket.emit (node:events:527:28)
    at TCP.<anonymous> (node:net:709:12)

**Comment by caseyjhol** [comment]
Resolved in v1.0.1
